'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, BookOpen, CalendarDays, Check, ChevronDown, CircleHelp, Download, Filter, Gauge, LayoutDashboard, LineChart, MessageSquareText, Plus, Search, Settings2, Sparkles, Target, Trash2, X } from 'lucide-react';
import { keywordGroups } from '@/lib/keywords';

type RankRow = { keyword: string; group: string; rank: number | null; change: number | null; checked: boolean };
type ReviewRecord = { date: string; visitor: number | null; blog: number | null; source: string };
type DashboardPayload = { version?: number; mode?: string; date?: string; rankSource?: string; rankings?: RankRow[]; review?: { history?: ReviewRecord[] } };
const DASHBOARD_DATA_URL = 'https://raw.githubusercontent.com/song7789-web/thera-pt-naver-rank-dashboard/main/public/data/dashboard.json';

const sampleRanks: Record<string, number> = {};
const allRows: RankRow[] = Object.entries(keywordGroups).flatMap(([group, words]) => words.map((keyword, index) => ({ keyword, group, rank: sampleRanks[keyword] ?? null, change: sampleRanks[keyword] ? (index % 3 === 0 ? 2 : index % 3 === 1 ? -1 : 0) : null, checked: Boolean(sampleRanks[keyword]) })));
const initialReviewRecords: ReviewRecord[] = [
  { date: '2026.09.05', visitor: null, blog: null, source: '첨부 화면 기준 참고값 577개' },
];

function RankBadge({ rank }: { rank: number | null }) { return rank ? <span className={`rank-number ${rank <= 10 ? 'is-top' : ''}`}>{rank}위</span> : <span className="rank-empty">미수집</span>; }

export default function Home() {
  const [activeGroup, setActiveGroup] = useState('전체 키워드'); const [query, setQuery] = useState(''); const [view, setView] = useState<'all'|'top'|'missing'>('all'); const [keywords, setKeywords] = useState(allRows); const [newKeyword, setNewKeyword] = useState(''); const [showAdd, setShowAdd] = useState(false); const [reviewRecords, setReviewRecords] = useState(initialReviewRecords); const [showReviewAdd, setShowReviewAdd] = useState(false); const [visitorInput, setVisitorInput] = useState(''); const [blogInput, setBlogInput] = useState(''); const [syncMessage, setSyncMessage] = useState(''); const [dataSource, setDataSource] = useState<'setup'|'live'>('setup'); const [rankSource, setRankSource] = useState('실제 네이버 플레이스 순위가 아직 수집되지 않았습니다.'); const [collectionDate, setCollectionDate] = useState('수집 전');
  useEffect(() => { async function loadDashboard() { for (const url of [`${DASHBOARD_DATA_URL}?v=${Date.now()}`, '/data/dashboard.json']) { try { const response = await fetch(url, { cache: 'no-store' }); if (!response.ok) continue; const payload = await response.json() as DashboardPayload; if (payload.version !== 2 || payload.mode !== 'live' || !Array.isArray(payload.rankings)) continue; setKeywords(payload.rankings); setDataSource('live'); setRankSource(payload.rankSource ?? '네이버 플레이스 관련도순 · 광고 제외'); setCollectionDate(payload.date ?? '날짜 미확인'); if (payload.review?.history?.length) setReviewRecords(payload.review.history); return; } catch { /* 다음 데이터 주소 확인 */ } } } void loadDashboard(); }, []);
  useEffect(() => { fetch('/api/reviews').then(response => response.ok ? response.json() as Promise<{ history?: ReviewRecord[] }> : null).then(payload => { if (payload?.history?.length) setReviewRecords(payload.history); }).catch(() => undefined); }, []);
  const filtered = useMemo(() => keywords.filter(row => (activeGroup === '전체 키워드' || row.group === activeGroup) && row.keyword.toLowerCase().includes(query.toLowerCase()) && (view === 'all' || (view === 'top' ? Boolean(row.rank && row.rank <= 10) : !row.rank))), [activeGroup, keywords, query, view]);
  const checkedCount = keywords.filter(item => item.checked).length; const topTen = keywords.filter(item => item.rank && item.rank <= 10).length; const average = checkedCount ? Math.round(keywords.filter(item => item.rank).reduce((sum, item) => sum + (item.rank ?? 0), 0) / checkedCount) : null;
  function addKeyword() { const value = newKeyword.trim(); if (!value || keywords.some(item => item.keyword === value)) return; setKeywords(items => [{keyword:value,group:'직접 추가',rank:null,change:null,checked:false}, ...items]); setNewKeyword(''); setShowAdd(false); }
  const latestReview = reviewRecords[0]; const referenceTotal = latestReview.visitor !== null && latestReview.blog !== null ? latestReview.visitor + latestReview.blog : 577;
  async function addReviewRecord() { const visitor = Number(visitorInput); const blog = Number(blogInput); if (!Number.isFinite(visitor) || !Number.isFinite(blog) || visitor < 0 || blog < 0 || visitorInput === '' || blogInput === '') return; const nextRecord = { date: '2026.09.05', visitor, blog, source: '직접 입력' }; try { await fetch('/api/reviews', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ date: '2026-09-05', visitorReviews: visitor, blogReviews: blog }) }); } catch { /* 로컬 화면 기록은 계속 유지 */ } setReviewRecords(records => [nextRecord, ...records.filter(record => record.date !== '2026.09.05')]); setVisitorInput(''); setBlogInput(''); setShowReviewAdd(false); }
  async function checkConnection() { setSyncMessage('연결 확인 중...'); try { const response = await fetch('/api/naver-sync'); const data = await response.json() as { connected?: boolean; message?: string }; setSyncMessage(data.message ?? (data.connected ? '실제 플레이스 화면 수집 연결됨' : '수집 연결 확인 필요')); } catch { setSyncMessage('서버 연결 확인 필요'); } }
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand-mark"><span>TP</span><div><strong>테라PT</strong><small>언주역점</small></div></div><nav className="side-nav" aria-label="주요 메뉴"><button className="nav-item active"><LayoutDashboard size={18}/>순위 대시보드</button><button className="nav-item"><LineChart size={18}/>순위 추이</button><button className="nav-item"><Target size={18}/>키워드 관리</button></nav><div className="side-divider"/><div className="side-label">키워드 그룹</div><div className="group-list">{['전체 키워드', ...Object.keys(keywordGroups)].map(group => <button key={group} className={`group-item ${activeGroup === group ? 'selected' : ''}`} onClick={() => setActiveGroup(group)}><span className="group-dot"/>{group}<em>{group === '전체 키워드' ? keywords.length : keywords.filter(item => item.group === group).length}</em></button>)}</div><button className="settings-link"><Settings2 size={17}/>설정</button></aside>
    <section className="main-content"><header className="topbar"><div className="breadcrumb">순위 대시보드 <span>/</span> 오늘의 현황</div><div className="top-actions"><button className="icon-button" aria-label="도움말"><CircleHelp size={19}/></button><button className="profile-chip"><span>관</span> 관리자 <ChevronDown size={15}/></button></div></header>
      <div className="page-wrap"><div className="page-heading"><div><div className="eyebrow"><span className="live-dot"/> DAILY CHECK</div><h1>오늘의 네이버 순위</h1><p>테라PT 언주역점의 핵심 키워드가 어디에 노출되고 있는지 확인하세요.</p></div><div className="date-control"><CalendarDays size={17}/><span>2026년 9월 5일</span><ChevronDown size={15}/></div></div>
        <div className={`notice ${dataSource === 'live' ? 'is-live' : ''}`}><div className="notice-icon"><Sparkles size={17}/></div><div><strong>{syncMessage || (dataSource === 'live' ? '자동 수집 연결됨' : '실제 순위 수집 대기 중')}</strong><span>{dataSource === 'live' ? '네이버 플레이스 관련도순에서 광고를 제외한 실제 업체 순위입니다. 언주역점 위치를 고정 기준으로 사용합니다.' : '검증되지 않은 예시 순위는 표시하지 않습니다. GitHub Actions가 실제 플레이스 화면을 수집하면 자동으로 갱신됩니다.'}</span></div><button className="sync-check-button" onClick={checkConnection}>연결 확인</button></div>
        <div className="review-card"><div className="review-head"><div><div className="section-kicker"><MessageSquareText size={15}/> REVIEW TRACKING</div><h2>리뷰 수 일별 트래킹</h2><p>방문자 리뷰와 블로그 리뷰를 합산해 날짜별 증가 흐름을 기록합니다.</p></div><button className="secondary-button" onClick={() => setShowReviewAdd(true)}><Plus size={16}/> 오늘 기록 입력</button></div><div className="review-summary"><div className="review-total"><span>통합 리뷰 수</span><strong>{referenceTotal}<small>개</small></strong><em>{latestReview.visitor !== null ? '직접 입력한 최신 기록' : '첨부 화면 기준 참고값'}</em></div><div className="review-source"><div className="source-icon visitor"><MessageSquareText size={17}/></div><div><span>방문자 리뷰</span><strong>{latestReview.visitor !== null ? `${latestReview.visitor}개` : '연결 필요'}</strong></div></div><div className="review-source"><div className="source-icon blog"><BookOpen size={17}/></div><div><span>블로그 리뷰</span><strong>{latestReview.blog !== null ? `${latestReview.blog}개` : '연결 필요'}</strong></div></div><div className="review-status"><span className="status-dot"/> 자동 수집 연결 전<p>매일 기록을 입력하거나<br/>수집 연결 후 자동 업데이트</p></div></div><div className="review-history"><div className="history-title"><strong>일별 기록</strong><span>방문자 + 블로그 = 통합 리뷰</span></div><table><thead><tr><th>날짜</th><th>방문자 리뷰</th><th>블로그 리뷰</th><th>통합 리뷰</th><th>기록 방식</th></tr></thead><tbody>{reviewRecords.map(record => <tr key={record.date}><td>{record.date}</td><td>{record.visitor === null ? <span className="rank-empty">확인 필요</span> : `${record.visitor}개`}</td><td>{record.blog === null ? <span className="rank-empty">확인 필요</span> : `${record.blog}개`}</td><td><strong>{record.visitor !== null && record.blog !== null ? `${record.visitor + record.blog}개` : '577개'}</strong></td><td><span className={`history-source ${record.visitor === null ? 'reference' : ''}`}>{record.source}</span></td></tr>)}</tbody></table></div></div>
        <div className="stats-grid"><div className="stat-card primary-stat"><div className="stat-top"><span>전체 키워드</span><div className="stat-icon"><Gauge size={19}/></div></div><strong>{keywords.length}<small>개</small></strong><p>관리 중인 키워드</p></div><div className="stat-card"><div className="stat-top"><span>상위 10위</span><div className="stat-icon green"><ArrowUpRight size={19}/></div></div><strong>{topTen}<small>개</small></strong><p className="positive">{dataSource === 'live' ? '실제 플레이스 기준' : '수집 대기 중'}</p></div><div className="stat-card"><div className="stat-top"><span>평균 순위</span><div className="stat-icon purple"><Target size={19}/></div></div><strong>{average ?? '-'}<small>{average ? '위' : ''}</small></strong><p className="positive">실제 확인 {checkedCount}개 기준</p></div><div className="stat-card"><div className="stat-top"><span>확인 완료</span><div className="stat-icon amber"><Check size={19}/></div></div><strong>{checkedCount}<small>/{keywords.length}</small></strong><p>수집일 {collectionDate}</p></div></div>
        <div className="table-card"><div className="table-head"><div><h2>키워드별 순위</h2><p>{rankSource}</p></div><div className="table-actions"><button className="secondary-button"><Download size={16}/> 내보내기</button><button className="primary-button" onClick={() => setShowAdd(true)}><Plus size={17}/> 키워드 추가</button></div></div><div className="toolbar"><div className="search-box"><Search size={17}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="키워드 검색" aria-label="키워드 검색"/></div><div className="view-tabs"><button className={view === 'all' ? 'active' : ''} onClick={() => setView('all')}>전체 <span>{keywords.length}</span></button><button className={view === 'top' ? 'active' : ''} onClick={() => setView('top')}>상위 10위 <span>{topTen}</span></button><button className={view === 'missing' ? 'active' : ''} onClick={() => setView('missing')}>미수집 <span>{keywords.length - checkedCount}</span></button></div><button className="filter-button"><Filter size={16}/> 필터 <ChevronDown size={14}/></button></div><div className="table-scroll"><table><thead><tr><th>키워드</th><th>그룹</th><th>현재 순위</th><th>변동</th><th>확인 상태</th><th aria-label="관리"/></tr></thead><tbody>{filtered.map((row, index) => <tr key={`${row.keyword}-${row.group}-${index}`}><td><span className="keyword-name">{row.keyword}</span>{row.rank && row.rank <= 10 ? <span className="top-tag">TOP 10</span> : null}</td><td><span className="group-pill">{row.group}</span></td><td><RankBadge rank={row.rank}/></td><td>{row.change === null ? <span className="muted">-</span> : row.change > 0 ? <span className="rank-down"><ArrowDownRight size={14}/> {row.change}</span> : row.change < 0 ? <span className="rank-up"><ArrowUpRight size={14}/> {Math.abs(row.change)}</span> : <span className="same">-</span>}</td><td>{row.checked ? <span className="status checked"><span/> 확인 완료</span> : <span className="status waiting"><span/> 50위 밖/확인 필요</span>}</td><td><button className="row-delete" onClick={() => setKeywords(items => items.filter(item => item !== row))} aria-label={`${row.keyword} 삭제`}><Trash2 size={15}/></button></td></tr>)}</tbody></table>{filtered.length === 0 ? <div className="empty-state">조건에 맞는 키워드가 없습니다.</div> : null}</div><div className="table-foot"><span>총 {filtered.length}개 키워드</span><span className="foot-help"><CircleHelp size={14}/> 순위는 검색 위치·시간에 따라 달라질 수 있습니다.</span></div></div>
      </div></section>
    {showAdd ? <dialog open className="modal-backdrop"><div className="add-modal"><button className="modal-close" onClick={() => setShowAdd(false)}><X size={18}/></button><div className="modal-icon"><Plus size={20}/></div><h3 id="add-keyword-title">키워드 추가</h3><p>매일 확인할 네이버 검색 키워드를 추가하세요.</p><label htmlFor="new-keyword">키워드</label><input id="new-keyword" value={newKeyword} onChange={event => setNewKeyword(event.target.value)} onKeyDown={event => event.key === 'Enter' && addKeyword()} placeholder="예: 언주역필라테스"/><div className="modal-buttons"><button className="secondary-button" onClick={() => setShowAdd(false)}>취소</button><button className="primary-button" onClick={addKeyword}>추가하기</button></div></div></dialog> : null}
    {showReviewAdd ? <dialog open className="modal-backdrop"><div className="add-modal"><button className="modal-close" onClick={() => setShowReviewAdd(false)}><X size={18}/></button><div className="modal-icon review-modal-icon"><MessageSquareText size={20}/></div><h3>오늘 리뷰 수 기록</h3><p>네이버 플레이스에서 확인한 두 숫자를 입력하면 통합 리뷰 수를 계산합니다.</p><label htmlFor="visitor-review">방문자 리뷰</label><input id="visitor-review" type="number" min="0" value={visitorInput} onChange={event => setVisitorInput(event.target.value)} placeholder="예: 531"/><label htmlFor="blog-review">블로그 리뷰</label><input id="blog-review" type="number" min="0" value={blogInput} onChange={event => setBlogInput(event.target.value)} placeholder="예: 46"/><div className="modal-total">통합 리뷰 <strong>{(Number(visitorInput) || 0) + (Number(blogInput) || 0)}개</strong></div><div className="modal-buttons"><button className="secondary-button" onClick={() => setShowReviewAdd(false)}>취소</button><button className="primary-button" onClick={addReviewRecord}>오늘 기록 저장</button></div></div></dialog> : null}
  </main>;
}
